project:
  type: website
  output-dir: _site

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "From Map to Analysis"
  navbar:
    tools:
      - icon: github
        href: https://github.com/UCSB-Library-Research-Data-Services/from-maps-to-analysis
    left:
      - href: 01_make_map.qmd
        text: "Make a map"
      - href: 02_intro_gis.qmd
        text: "Intro to GIS"
      - href: 03_geospatial_analysis.qmd
        text: "Geospatial Analysis"
format:
  html:
    css: styles.scss
    toc: true
    page-layout: full
    code-line-numbers: false
    code-fold: false
    code-tools: true



