project:
  type: website

website:
  title: "From Map to Analysis"
  navbar:
    left:
      - href: 01_make_map.qmd
        text: "Make a map"
      - href: 02_intro_gis.qmd
        text: "Intro to GIS"
      - href: 03_geospatial_analysis.qmd
        text: "Geospatial Analysis"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



