---
title: "From Maps to Analysis"
author:
  - name: Julien Brun
    url: https://brunj7.github.io/
    orcid: 0000-0002-7751-6238
  - name: Jon Jablonski
  - name: Kristi Liu
  - name: Jairo Melo Flórez
    orcid: 0000-0002-2020-1163
  - name: Greg Janée
    url: https://www.library.ucsb.edu/staff/greg-janee
    orcid: 0000-0001-8785-0021

date: last-modified
citation: 
  url: https://ucsb-library-research-data-services.github.io/from-maps-to-analysis/
categories: [GIS, map, geospatial analysis]
---

The goal of this workshop series is to provide a gentle introduction to creating maps and conducting geospatial analysis without the need to have programming skills.

We have organized this curriculum into three workshops:

## Workshop 1 - I want to make a map

2-hour workshop using ArcGIS Online to create a map. This workshop will introduce the basic elements of a map and leverage ArcGIS Online to learn how to:

-   adjust the background basemap
-   add an existing layer to a map
-   change symbology
-   draw lines and polygons on a map

The workshop ends with exporting a map suitable for inclusion in a publication.

## Workshop 2 - I think I need GIS

2-3 hours workshop using ArcGIS Online to conduct basic GIS data manipulations.

-   data import & export
-   projections
-   raster and vector data

Ends with an analysis, maybe zonal statistics?

## Workshop 3 - Geospatial analysis

4-hour workshop. Carpentry-like in ArcGIS Pro

Data analysis centric:

-   buffering
-   interpolation
-   zonal statistics
-   raster calculation
